<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Inicio de Sesión',
        'headline' => 'Inicio de Sesión',
        'subheadline' => 'Inicia sesón en tu cuenta debajo',
        'show_subheadline' => false,
        'email_address' => 'Dirección de Correo Electrónico',
        'password' => 'Contraseña',
        'remember_me' => 'Recuérdame',
        'edit' => 'Editar',
        'button' => 'Continuar',
        'forget_password' => '¿Has olvidado tu contraseña?',
        'dont_have_an_account' => '¿No tienes una cuenta?',
        'sign_up' => 'Regístrate',
        'social_auth_authenticated_message' => 'You have been authenticated via __social_providers_list__. Inicia sesón con una de las redes de la parte inferior.',
        'change_email' => 'Cambio de Email',
    ],
    'register' => [
        'page_title' => 'Registro',
        'headline' => 'Regístrate',
        'subheadline' => 'Register for your free account below.',
        'show_subheadline' => false,
        'name' => 'Nombre',
        'email_address' => 'Correo Electrónico',
        'password' => 'Contraseña',
        'password_confirmation' => 'Confima la contraseña',
        'already_have_an_account' => '¿Ya tienes una cuenta?',
        'sign_in' => 'Inicia Sesión',
        'button' => 'Continuar',
    ],
    'verify' => [
        'page_title' => 'Verifica tu cuenta',
        'headline' => 'Verifica tu email',
        'subheadline' => 'Before you can proceed you must verify your email.',
        'show_subheadline' => false,
        'description' => 'Antes de continuar, compruebe si ha recibido un enlace de verificación en su correo electrónico. Si no ha recibido el correo electrónico,',
        'new_request_link' => 'haz clic aquí para solicitar otro.',
        'new_link_sent' => 'Se ha enviado un nuevo enlace a tu dirección de correo electrónico.',
        'or' => 'O',
        'logout' => 'haz clic aquí para cerrar la sesión.',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirma tu contraseña',
        'headline' => 'Confirmar Contraseña',
        'subheadline' => 'Be sure to confirm your password below',
        'show_subheadline' => false,
        'password' => 'Contraseña',
        'button' => 'Confirmar Contraseña',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Solicitar un restablecimiento de contraseña',
        'headline' => 'Restablecer contraseña',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Correo Electrónico',
        'button' => 'Enviar enlace para restablecer contraseña',
        'or' => 'O',
        'return_to_login' => 'volver al inicio de sesión',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
